// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXtAJmS9JiIBrUP4BoCkfeV172R2HRKD8',
    appId: '1:504364713685:web:be611c55f870aa47d7445c',
    messagingSenderId: '504364713685',
    projectId: 'falldetection-2b1dd',
    authDomain: 'falldetection-2b1dd.firebaseapp.com',
    databaseURL: 'https://falldetection-2b1dd-default-rtdb.firebaseio.com',
    storageBucket: 'falldetection-2b1dd.appspot.com',
    measurementId: 'G-MWZXDNT28T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcdMoOhiKd4jgzAbXhO5uxMkYlSUhJFfs',
    appId: '1:504364713685:android:5e166165ff543b4cd7445c',
    messagingSenderId: '504364713685',
    projectId: 'falldetection-2b1dd',
    databaseURL: 'https://falldetection-2b1dd-default-rtdb.firebaseio.com',
    storageBucket: 'falldetection-2b1dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJCVLaJ4i-5WZSVP0od-LxwrE2RebAXU',
    appId: '1:504364713685:ios:1e9674ab1d67d259d7445c',
    messagingSenderId: '504364713685',
    projectId: 'falldetection-2b1dd',
    databaseURL: 'https://falldetection-2b1dd-default-rtdb.firebaseio.com',
    storageBucket: 'falldetection-2b1dd.appspot.com',
    iosBundleId: 'com.example.vorviewadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJCVLaJ4i-5WZSVP0od-LxwrE2RebAXU',
    appId: '1:504364713685:ios:1e9674ab1d67d259d7445c',
    messagingSenderId: '504364713685',
    projectId: 'falldetection-2b1dd',
    databaseURL: 'https://falldetection-2b1dd-default-rtdb.firebaseio.com',
    storageBucket: 'falldetection-2b1dd.appspot.com',
    iosBundleId: 'com.example.vorviewadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXtAJmS9JiIBrUP4BoCkfeV172R2HRKD8',
    appId: '1:504364713685:web:f57f7c62e2860c08d7445c',
    messagingSenderId: '504364713685',
    projectId: 'falldetection-2b1dd',
    authDomain: 'falldetection-2b1dd.firebaseapp.com',
    databaseURL: 'https://falldetection-2b1dd-default-rtdb.firebaseio.com',
    storageBucket: 'falldetection-2b1dd.appspot.com',
    measurementId: 'G-Y98ZKZ3QK8',
  );
}
